# Header
menu:
  Home: /
  Archives: /archives
  About: about

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /blog/img/home-bg.jpg
archive_cover: /blog/img/archive-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Duoshuo comments
  duoshuo_shortname: liangjingzhan
  # 多说分享服务，必须与多说评论同时使用
  duoshuo_share: true
  # Disqus comments
  # disqus_shortname: httpliangjingzhangithubio
  # Facebook comments
  # facebook:
  # appid:
  #  comment_count: 5
  #  comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
facebook_url:
weibo_url: http://weibo.com/fatzhana
github_url: https://github.com/liangjingzhan